version: '3.8'
services:
  postgres:
    # ... (existing config)
    image: postgres
    environment:
      POSTGRES_USER: hassan
      POSTGRES_PASSWORD: password
    volumes:
      - ./database-data:/var/lib/postgresql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hassan" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=ecommercedb
      - DATABASE_USER=hassan
      - DATABASE_PASSWORD=password
      - JWT_SECRET=keep-this-secret-private
      - PORT=3000
    depends_on:
      postgres:
        condition: service_healthy
